export const INDUSTRIES = [
  'All industries',
  'Accounting',
  'Airlines/Aviation',
  'Alternative Dispute Resolution',
  'Alternative Medicine',
  'Animation',
  'Apparel & Fashion',
  'Architecture & Planning',
  'Arts and Crafts',
  'Automotive',
  'Aviation & Aerospace',
  'Banking',
  'Biotechnology',
  'Broadcast Media',
  'Building Materials',
  'Business Supplies and Equipment',
  'Capital Markets',
  'Chemicals',
  'Civic & Social Organization',
  'Civil Engineering',
  'Commercial Real Estate',
  'Computer & Network Security',
  'Computer Games',
  'Computer Hardware',
  'Computer Networking',
  'Computer Software',
  'Construction',
  'Consumer Electronics',
  'Consumer Goods',
  'Consumer Services',
  'Cosmetics',
  'Dairy',
  'Defense & Space',
  'Design',
  'Education Management',
  'E-learning',
  'Electrical/Electronic Manufacturing',
  'Entertainment',
  'Environmental Services',
  'Events Services',
  'Executive Office',
  'Facilities Services',
  'Farming',
  'Financial Services',
  'Fine Art',
  'Fishery',
  'Food & Beverages',
  'Food Production',
  'Fundraising',
  'Furniture',
  'Gambling & Casinos',
  'Glass, Ceramics & Concrete',
  'Government Administration',
  'Government Relations',
  'Graphic Design',
  'Health, Wellness and Fitness',
  'Higher Education',
  'Hospital & Health Care',
  'Hospitality',
  'Human Resources',
  'Import and Export',
  'Individual & Family Services',
  'Industrial Automation',
  'Information Services',
  'Information Technology & Services',
  'Insurance',
  'International Affairs',
  'International Trade and Development',
  'Internet',
  'Investment Banking',
  'Investment Management',
  'Judiciary',
  'Law Enforcement',
  'Law Practice',
  'Legal Services',
  'Legislative Office',
  'Leisure, Travel & Tourism',
  'Libraries',
  'Logistics and Supply Chain',
  'Luxury Goods & Jewelry',
  'Machinery',
  'Management Consulting',
  'Maritime',
  'Market Research',
  'Marketing and Advertising',
  'Mechanical or Industrial Engineering',
  'Media Production',
  'Medical Devices',
  'Medical Practice',
  'Mental Health Care',
  'Military',
  'Mining & Metals',
  'Motion Pictures and Film',
  'Museums and Institutions',
  'Music',
  'Nanotechnology',
  'Newspapers',
  'Non-profit Organization Management',
  'Oil & Energy',
  'Online Media',
  'Outsourcing/Offshoring',
  'Package/Freight Delivery',
  'Packaging and Containers',
  'Paper & Forest Products',
  'Performing Arts',
  'Pharmaceuticals',
  'Philanthropy',
  'Photography',
  'Plastics',
  'Political Organization',
  'Primary/Secondary Education',
  'Printing',
  'Professional Training & Coaching',
  'Program Development',
  'Public Policy',
  'Public Relations and Communications',
  'Public Safety',
  'Publishing',
  'Railroad Manufacture',
  'Ranching',
  'Real Estate',
  'Recreational Facilities and Services',
  'Religious Institutions',
  'Renewables & Environment',
  'Research',
  'Restaurants',
  'Retail',
  'Security and Investigations',
  'Semiconductors',
  'Shipbuilding',
  'Sporting Goods',
  'Sports',
  'Staffing and Recruiting',
  'Supermarkets',
  'Telecommunications',
  'Textiles',
  'Think Tanks',
  'Tobacco',
  'Translation and Localization',
  'Transportation/Trucking/Railroad',
  'Utilities',
  'Venture Capital & Private Equity',
  'Veterinary',
  'Warehousing',
  'Wholesale',
  'Wine and Spirits',
  'Wireless',
  'Writing and Editing',
  'Education Technology',
  'EdTech',
  'Educational Services',
  'E-commerce',
  'Digital Marketing',
  'Social Media',
  'Mobile Apps',
  'Cloud Computing',
  'Artificial Intelligence',
  'Machine Learning',
  'Data Science',
  'Big Data',
  'Blockchain',
  'Cryptocurrency',
  'FinTech',
  'HealthTech',
  'MedTech',
  'CleanTech',
  'GreenTech',
  'Smart Cities',
  'IoT',
  'Internet of Things',
  'Robotics',
  'Virtual Reality',
  'Augmented Reality',
  'Gaming',
  'Esports',
  'Digital Media',
  'Content Creation',
  'Digital Advertising',
  'SEO/SEM',
  'Web Development',
  'Mobile Development',
  'Software Development',
  'IT Services',
  'IT Consulting',
  'IT Infrastructure',
  'IT Security',
  'IT Support',
  'IT Training',
  'IT Outsourcing',
  'IT Staffing',
  'IT Recruitment',
  'IT Project Management',
  'IT Business Analysis',
  'IT Quality Assurance',
  'IT Testing',
  'IT Maintenance',
  'IT Operations',
  'IT Strategy',
  'IT Architecture',
  'IT Integration',
  'IT Transformation',
  'IT Innovation',
  'IT Research',
  'IT Education',
  'IT Training',
  'IT Certification',
  'IT Consulting',
  'IT Advisory',
  'IT Management',
  'IT Governance',
  'IT Risk Management',
  'IT Compliance',
  'IT Audit',
  'IT Security',
  'IT Privacy',
  'IT Data Protection',
  'IT Disaster Recovery',
  'IT Business Continuity',
  'IT Service Management',
  'IT Service Desk',
  'IT Help Desk',
  'IT Support',
  'IT Maintenance',
  'IT Operations',
  'IT Infrastructure',
  'IT Network',
  'IT Systems',
  'IT Applications',
  'IT Software',
  'IT Hardware',
  'IT Cloud',
  'IT Data Center',
  'IT Storage',
  'IT Backup',
  'IT Recovery',
  'IT Security',
  'IT Privacy',
  'IT Compliance',
  'IT Risk',
  'IT Governance',
  'IT Strategy',
  'IT Architecture',
  'IT Design',
  'IT Development',
  'IT Testing',
  'IT Deployment',
  'IT Operations',
  'IT Maintenance',
  'IT Support',
  'IT Service',
  'IT Management',
  'IT Consulting',
  'IT Advisory',
  'IT Training',
  'IT Education',
  'IT Research',
  'IT Innovation',
  'IT Transformation',
  'IT Integration',
  'IT Project',
  'IT Program',
  'IT Portfolio',
  'IT Business',
  'IT Enterprise',
  'IT Organization',
  'IT Department',
  'IT Team',
  'IT Staff',
  'IT Personnel',
  'IT Professional',
  'IT Specialist',
  'IT Expert',
  'IT Consultant',
  'IT Advisor',
  'IT Trainer',
  'IT Educator',
  'IT Researcher',
  'IT Innovator',
  'IT Transformer',
  'IT Integrator',
  'IT Project Manager',
  'IT Program Manager',
  'IT Portfolio Manager',
  'IT Business Analyst',
  'IT Enterprise Architect',
  'IT Organization Designer',
  'IT Department Head',
  'IT Team Lead',
  'IT Staff Manager',
  'IT Personnel Director',
  'IT Professional Development',
  'IT Specialist Training',
  'IT Expert Consulting',
  'IT Consultant Services',
  'IT Advisory Services',
  'IT Training Services',
  'IT Education Services',
  'IT Research Services',
  'IT Innovation Services',
  'IT Transformation Services',
  'IT Integration Services',
  'IT Project Services',
  'IT Program Services',
  'IT Portfolio Services',
  'IT Business Services',
  'IT Enterprise Services',
  'IT Organization Services',
  'IT Department Services',
  'IT Team Services',
  'IT Staff Services',
  'IT Personnel Services',
  'IT Professional Services',
  'IT Specialist Services',
  'IT Expert Services',
  'IT Consultant Services',
  'IT Advisor Services',
  'IT Trainer Services',
  'IT Educator Services',
  'IT Researcher Services',
  'IT Innovator Services',
  'IT Transformer Services',
  'IT Integrator Services',
  'IT Project Manager Services',
  'IT Program Manager Services',
  'IT Portfolio Manager Services',
  'IT Business Analyst Services',
  'IT Enterprise Architect Services',
  'IT Organization Designer Services',
  'IT Department Head Services',
  'IT Team Lead Services',
  'IT Staff Manager Services',
  'IT Personnel Director Services'
];

export const EMPLOYEE_RANGES = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10000+"
];